### ISSUE TITLE
shortcut doesn't work

### ISSUE THREAD

**Issue by tjx666** [zachhardesty7/jsdoc-comment-toggler#15]
![image](https://user-images.githubusercontent.com/41773861/225540798-4a1d5cf6-a20b-4cbd-85b7-f9192e795555.png)

![image](https://user-images.githubusercontent.com/41773861/225540839-5021da14-3d3d-4a29-a418-ccc371af94bc.png)

I think extension shouldn't add shortcut, becuase user can define it easily

**Comment by zachhardesty7** [comment]
Published a new version which changes the shortcut to use `cmd+r cmd+/` or `ctrl+r ctrl+/`. I feel like it's slightly better to include some builtin keyboard shortcut. It probably doesn't matter much anyway, but it's there just in case.
